services:
  client:
    build: ./apps/client
    ports:
      - "3000:3000"

  api:
    build: ./apps/api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  ai-core:
    build: ./apps/ai-core
    ports:
      - "8000:8000"
