name: Deploy ThinklineAI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: ./apps/client
          tags: your-registry/client:latest
          push: true

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          tags: your-registry/api:latest
          push: true

      - name: Build and push AI core
        uses: docker/build-push-action@v5
        with:
          context: ./apps/ai-core
          tags: your-registry/ai-core:latest
          push: true
